name: cs307-team26-boilerbridge
region: nyc3
services:
  - name: boilerbridge-web
    image:
      registry_type: DOCR
      repository: boilerbridge-registry/boilerbridge
      tag: ${IMAGE_TAG_BOILERBRIDGE_WEB}
    run_command: node server.js
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xs
    envs:
      - key: NPM_CONFIG_LEGACY_PEER_DEPS
        scope: RUN_TIME
        value: "true"
      - key: NEXT_TELEMETRY_DISABLED
        scope: RUN_TIME
        value: "1"
      - key: NODE_ENV
        scope: RUN_TIME
        value: "production"
      - key: NEXTAUTH_URL
        scope: RUN_TIME
        value: ${APP_URL}
      - key: NEXTAUTH_SECRET
        scope: RUN_TIME
        value: ${NEXTAUTH_SECRET}
        type: SECRET
      - key: MONGODB_URI
        scope: RUN_AND_BUILD_TIME
        value: ${MONGODB_URI}
        type: SECRET
