name: Delete Preview

on:
  pull_request:
    types: [closed]

jobs:
  closed:
    runs-on: ubuntu-latest
    steps:
      - name: delete preview app
        uses: digitalocean/app_action/delete@v2
        with:
          from_pr_preview: "true"
          ignore_not_found: "true"
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Delete registry image
        run: |
          doctl registry repository delete-manifest boilerbridge pr-${{ github.event.number }} --force
          doctl registry garbage-collection start --include-untagged-manifests --force